name: Rugby King
favicon: null
layout_spectrum: 0.03539764625020325
typography_spectrum: 0.6699867111165076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6075810336042196
  lightness: 0.3949686880223453
  saturation: 0.24600603361614048
  rhythmicContrast: 0.3082746625877917
purpose: []
