name: Rugby King
favicon: null
layout_spectrum: 0.49552
typography_spectrum: 0.24668
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#24272c'
    - '#875145'
    - '#d29612'
    - '#f4cf43'
    - '#7f885d'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
