name: Rugby King
favicon: null
layout_spectrum: 0.2399
typography_spectrum: 0.24668
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070906'
    - '#52883c'
    - '#d3f8fe'
    - '#d8372a'
    - '#83a9bc'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
